# Generated by Django 3.1.7 on 2021-04-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210419_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=100, null=True)),
                ('line2', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='_value',
        ),
        migrations.AddField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bid amount in Euro.', max_digits=8, verbose_name='bid amount, EUR'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='auctions.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='auctions.address'),
        ),
    ]
