# Generated by Django 3.1.7 on 2021-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210420_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AddField(
            model_name='listing',
            name='_status',
            field=models.CharField(default='not started yet', max_length=20),
        ),
    ]
