# Generated by Django 3.1.7 on 2021-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210422_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='_status',
        ),
        migrations.AddField(
            model_name='listing',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
