# Generated by Django 3.1.7 on 2021-07-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210601_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('DL', 'Delivery address'), ('BL', 'Billing address')], default='DL', max_length=2),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='email_type',
            field=models.CharField(choices=[('CT', 'Contact'), ('PT', 'Payment')], default='CT', max_length=2),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL, verbose_name='user placed the bid'),
        ),
    ]
