# Generated by Django 3.1.7 on 2021-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210701_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
    ]
