# Generated by Django 3.1.7 on 2021-07-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_user_registration_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
