# Generated by Django 3.1.7 on 2021-07-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_user_registration_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registration_completed',
            new_name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_confirmed',
        ),
    ]
