# Generated by Django 3.2.7 on 2021-09-14 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210830_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='listing',
            name='cancelled_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='payment_policy',
            field=models.TextField(default='The seller will send information about the payment to the winner within                 2 business days after the auction end. \n                The winner can initiate a dispute or cancel the order if information                 required for payment was not received from the seller in due time. \n                The seller has a right to cancel the order if the payment was not                 received in due\ttime, amount due or due order as requested. In this                 case the seller shall return funds received after the term / not in                 due order to the buyer within 3\tbusiness days after their receipt. The                 seller has a right to withdraw from the funds to be returned an amount                 required to cover reasonable actual expenses related to the funds                 return.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='shipment_policy',
            field=models.TextField(default="The product will be shipped to the auction winner within 5 business                 days after the payment receipt. \n                The seller may request from the winner additional information                 reasonably required for shipment. In this case the product will be                 shipped within 3 business days after receipt of the requested                 information.\n                The winner has a right to open a dispute and request funds' return in                 case the product was not delivered to the winner within 45 days after                 the payment."),
        ),
    ]
