# Generated by Django 3.2.6 on 2021-09-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210914_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cancelled_on',
            field=models.DateTimeField(null=True),
        ),
    ]
