# Generated by Django 3.1.7 on 2021-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_cancelled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='/home/muhoed/Documents/Programming/CS50 web/cs50_web_python/commerce/static/images/cropped-placeholder.jpg', verbose_name="URL of product's image"),
        ),
        migrations.AlterField(
            model_name='listing',
            name='payment_policy',
            field=models.TextField(default='The seller will send information about the payment to the winner within 2 business days after the auction end. \nThe winner can initiate a dispute or cancel the order if information required for payment was not received from the seller in due time. \nThe seller has a right to cancel the order if the payment was not received in due\ttime, amount due or due order as requested. In this case the seller shall return funds received after the term / not in due order to the buyer within 3\tbusiness days after their receipt. The seller has a right to withdraw from the funds to be returned an amount required to cover reasonable actual expenses related to the funds return.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='shipment_policy',
            field=models.TextField(default="The product will be shipped to the auction winner within 5 business days after the payment receipt. \nThe seller may request from the winner additional information reasonably required for shipment. In this case the product will be shipped within 3 business days after receipt of the requested information.\nThe winner has a right to open a dispute and request funds' return in case the product was not delivered to the winner within 45 days after the payment."),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name="product's description"),
        ),
    ]
