# Generated by Django 3.1.7 on 2021-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20211008_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='/static/images/cropped-placeholder.jpg', verbose_name="URL of product's image"),
        ),
    ]
