# Generated by Django 3.2.6 on 2021-10-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20211008_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, default='/static/auctions/images/cropped-placeholder.jpg', null=True, verbose_name="URL of product's image"),
        ),
    ]
