# Generated by Django 3.2.6 on 2021-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipment_status',
            field=models.IntegerField(choices=[(0, 'Not Shipped'), (1, 'Shipped'), (2, 'Delivered')], default=0, verbose_name='shipment status'),
        ),
    ]
