# Generated by Django 3.1.7 on 2021-11-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20211112_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(max_length=285, verbose_name='message subject'),
        ),
    ]
