version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=wgbackend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/wisegrocery
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wisegrocery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A wgbackend worker -l INFO
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=wgbackend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/wisegrocery
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A wgbackend beat -l INFO
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=wgbackend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/wisegrocery
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data: 