# Generated by Django 4.1.4 on 2023-01-04 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionrule',
            name='product',
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='products',
            field=models.ManyToManyField(db_column='ConvRule_Prod', to='wgapi.product'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='from_unit',
            field=models.IntegerField(choices=[(1, 'Liter'), (2, 'Milliliter'), (3, 'Gallon'), (4, 'gram'), (5, 'kilogram'), (6, 'pound'), (7, 'ounce'), (8, 'Piece'), (9, 'Pack'), (10, 'Can'), (11, 'Bottle'), (12, 'Cup'), (13, 'Spoon'), (14, 'Teaspoon')], db_column='ConvRule_From_Unit'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='to_unit',
            field=models.IntegerField(choices=[(1, 'Liter'), (2, 'Milliliter'), (3, 'Gallon'), (4, 'gram'), (5, 'kilogram'), (6, 'pound'), (7, 'ounce'), (8, 'Piece'), (9, 'Pack'), (10, 'Can'), (11, 'Bottle'), (12, 'Cup'), (13, 'Spoon'), (14, 'Teaspoon')], db_column='ConvRule_To_Unit'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='icon',
            field=models.TextField(choices=[('freezer.png', 'Freezer'), ('fridge.png', 'Fridge'), ('buffet.png', 'Buffet'), ('cupboard.png', 'Cupboard')], db_column='Eq_Icon', default='fridge.png'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Liter'), (2, 'Milliliter'), (3, 'Gallon'), (4, 'gram'), (5, 'kilogram'), (6, 'pound'), (7, 'ounce'), (8, 'Piece'), (9, 'Pack'), (10, 'Can'), (11, 'Bottle'), (12, 'Cup'), (13, 'Spoon'), (14, 'Teaspoon')], db_column='Prod_Min_Unit'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Liter'), (2, 'Milliliter'), (3, 'Gallon'), (4, 'gram'), (5, 'kilogram'), (6, 'pound'), (7, 'ounce'), (8, 'Piece'), (9, 'Pack'), (10, 'Can'), (11, 'Bottle'), (12, 'Cup'), (13, 'Spoon'), (14, 'Teaspoon')], db_column='PurchItem_Unit'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Liter'), (2, 'Milliliter'), (3, 'Gallon'), (4, 'gram'), (5, 'kilogram'), (6, 'pound'), (7, 'ounce'), (8, 'Piece'), (9, 'Pack'), (10, 'Can'), (11, 'Bottle'), (12, 'Cup'), (13, 'Spoon'), (14, 'Teaspoon')], db_column='RcpProd_Unit'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Liter'), (2, 'Milliliter'), (3, 'Gallon'), (4, 'gram'), (5, 'kilogram'), (6, 'pound'), (7, 'ounce'), (8, 'Piece'), (9, 'Pack'), (10, 'Can'), (11, 'Bottle'), (12, 'Cup'), (13, 'Spoon'), (14, 'Teaspoon')], db_column='StkItem_Unit'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2023, 1, 11, 23, 4, 21, 428764)),
        ),
    ]
