# Generated by Django 4.1.4 on 2023-01-10 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0003_conversionrule_type_alter_stockitem_use_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='allow_replacement_use',
            field=models.BooleanField(db_column='Conf_Allow_Replacement', default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='gen_shop_plan_on_min_stock',
            field=models.BooleanField(db_column='Conf_Gen_ShopPlan_MinStock', default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='gen_shop_plan_repeatedly',
            field=models.BooleanField(db_column='Conf_Gen_ShopPlan_Repeatedly', default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='nofity_on_purchase_plan_generated',
            field=models.BooleanField(db_column='Conf_Notify_Purchase_Plan_Gen', default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='nofity_on_shopping_plan_generated',
            field=models.BooleanField(db_column='Conf_Notify_Shop_Plan_Gen', default=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='notify_on_expiration_before',
            field=models.DurationField(db_column='Conf_Notify_Expired_Days', default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2023, 1, 17, 14, 2, 33, 523048)),
        ),
    ]
