# Generated by Django 4.1.4 on 2024-01-17 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0003_remove_product_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrule',
            name='products',
            field=models.ManyToManyField(blank=True, db_column='ConvRule_Prod', null=True, to='wgapi.product'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='equipment',
            field=models.ForeignKey(blank=True, db_column='StkItem_Equip', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wgapi.equipment'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2024, 1, 24, 10, 21, 53, 451718)),
        ),
    ]
