# Generated by Django 4.1.4 on 2024-01-17 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0004_alter_conversionrule_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='stock_items',
            field=models.ManyToManyField(db_column='Consumption_StockItems', to='wgapi.stockitem'),
        ),
        migrations.AlterField(
            model_name='conversionrule',
            name='products',
            field=models.ManyToManyField(db_column='ConvRule_Prod', to='wgapi.product'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2024, 1, 24, 10, 49, 54, 452095)),
        ),
    ]
