# Generated by Django 4.1.4 on 2023-01-10 13:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0004_alter_config_allow_replacement_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='gen_shop_plan_period',
            field=models.DurationField(blank=True, db_column='Conf_GenShopPlan_Periodicity', default=datetime.timedelta(days=7), null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(days=3))]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2023, 1, 17, 14, 10, 48, 657388)),
        ),
    ]
