# Generated by Django 4.1.4 on 2024-01-20 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0005_alter_consumption_stock_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_period',
            field=models.DurationField(blank=True, db_column='Prod_Use_Period', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='use_till',
            field=models.DateField(blank=True, db_column='PurchItem_Use_Till_Date', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_column='Rcp_Name', db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2024, 1, 27, 16, 13, 30, 232442)),
        ),
        migrations.AlterUniqueTogether(
            name='cookingplan',
            unique_together={('date', 'meal', 'created_by')},
        ),
    ]
