# Generated by Django 4.1.4 on 2023-02-06 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0005_alter_config_gen_shop_plan_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='nofity_on_purchase_plan_generated',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True, default=datetime.datetime(2023, 2, 13, 18, 37, 8, 566082)),
        ),
    ]
