# Generated by Django 4.1.4 on 2024-01-20 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0006_product_use_period_purchaseitem_use_till_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='use_period',
        ),
        migrations.AddField(
            model_name='config',
            name='default_expiration_period',
            field=models.DurationField(db_column='Conf_Default_Expiration_Period', default=datetime.timedelta(days=14)),
        ),
        migrations.AddField(
            model_name='product',
            name='expiraton_period',
            field=models.DurationField(blank=True, db_column='Prod_Expiration_Period', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='use_till',
            field=models.DateField(db_column='StkItem_Use_Till_Date', db_index=True),
        ),
    ]
