# Generated by Django 4.1.4 on 2024-01-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wgapi', '0008_purchaseitem_original_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='original_unit',
        ),
    ]
